name: Build & Push Docker image

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  IMAGE_NAME: arseniirudenko/leantime
permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    concurrency:
      group: docker-publish-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: arseniirudenko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Generate sensible tags/labels:
      # - latest on default branch pushes
      # - semver tags for git tags
      # - branch name and short SHA
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=ref,event=branch
            type=sha,format=short

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
